canonical/sdcore-github-workflows

.github/workflows/issues.yaml
This change is needed so sdcore charms can use this workflow.
=> Makes the workflow usable from different projects

.github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
Bumps LXD version to `5.17/stable` as `5.13/stable` is no longer available.
=> Bumps LXD version to 5.17/stable

.github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
Replaces fixed version of the LXD snap with `latest/stable`. 
CONTEXT:
Once in a while, older versions of the LXD snap are getting removed. When this happens, our tests start failing. LXD is used by Charmcraft to spin up a charm builder. This means that the LXD version doesn't really affect our software, so I think it's safe to use `latest/stable` instead of a fixed version.
=> fix: Replacing specific version of the LXD snap with latest/stable

.github/workflows/publish-charm.yaml
The charming actions project recently added support to read metadata from charmcraft.yaml. However this is not in a current release so we point to the specific git commit.
- https://github.com/canonical/charming-actions/pull/132
=> fix: Read metadata from charmcraft.yaml

.github/workflows/terraform.yaml
The Terraform modules could be stored in different directories in the repositories. If we search them only in a default folder, this causes the issues. Adding `working-directory` path as an input variable help to customize this path according to repository requirements.
=> fix: Adding `working-directory` as an input variable to the terraform workflow

.github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
bump juju version from 3.1 to 3.4
=> chore: bump juju to 3.4

.github/workflows/integration-test-with-multus.yaml, .github/workflows/publish-charm.yaml
This change will push to a branch under edge with the same name as the branch on which the job runs.
For example, a PR using a branch called `TELCO-1082-Publish-charms-and-snaps-to-branch-on-pull-request` would look like the following after a successful run:
```
charmcraft status sdcore-upf-k8s
Track    Base                  Channel                                                             Version    Revision    Resources                                  Expires at                                                      
latest   ubuntu 22.04 (amd64)  stable                                                              -          -           -                                                                                                          
candidate …
```
=> feat: Publish charms and snaps to branch on pull request

.github/workflows/integration-test-machine.yaml, .github/workflows/integration-test.yaml
The multus based integration test archives the tested charm on success, whereas the other two do not. In order to standardize the publication of charms from branches, we need all tests to behave the same.
=> fix: Standardizing the integration tests so they all publish on push

.github/workflows/publish-charm.yaml
Adds a new step that ensures there are no `/` characters in the branch name. This should address the issue with bots creating branches that use the `/` character.
=> chore: Sanitize branch name

.github/workflows/publish-charm.yaml
This is an attempt to fix the failures for Dependabot publishing developer charms.
According to [documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions), the token for Dependabot is always created with `read` permissions. This PR forces the `write` permissions on the publish charm job only.
=> chore: add write permission to publish charm job for Dependabot

.github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
GitHub runners currently have problem with:
```
/usr/bin/sudo apt-get update -yqq
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
/usr/bin/sudo apt-get update -yqq
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
/usr/bin/sudo apt-get update -yqq
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/In …
```
=> fix: Use Canonical self-hosted runners for integration tests

.github/workflows/build.yaml, .github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml, .github/workflows/publish-charm.yaml
We move the charm build process to its own workflow stage. We build the charm, we test it, and we publish it, all with the same artifact. 
**Do not merge! We will need to take the following actions:**
1. ~~Tag the existing workflows in this project~~ Done
3. ~~Use the tag in the individual NF CI workflows~~ (Done)
4. ~~Validate that the changes here work (see [this PR in the AMF](https://github.com/canonical/sdcore-amf-k8s-operator/pull/180))~~ (Done)
5. Merge this change here
6. Create a new major release for the github workflows (1.0.0)
7. Change the individual NF to use the new workflow v1.0.0 and adapt their integration tests code to take built charms as parameters using conftest. 
```
tox -e integration -- --charm_path=<vault charm path> \
```
1. This reduces the amount of resources …
=> feat: build charm in independent workflow step

.github/workflows/codeql-analysis.yml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml, .github/workflows/lint-report.yaml, .github/workflows/publish-charm.yaml, .github/workflows/static-analysis.yaml, .github/workflows/terraform.yaml, .github/workflows/unit-test.yaml, .github/workflows/update-libs.yaml
Changing default branch to `github_ref` reference
=> fix: Changing default branch to github_ref reference

.github/workflows/update-libs.yaml
Changing trigger from `workflow_dispatch` to `workflow_call`
=> fix: Changing trigger from workflow_dispatch to workflow_call

.github/workflows/promote.yaml
- Bumps the version of the `release-charm` action to 2.6.0 to support promotion of the charms not having the `metadata.yaml`
- Makes sure the right branch is checked out for promotion run
=> fix: Bumps version of the release-charm action to 2.6.0

.github/workflows/publish-charm.yaml
Fixes charm publishing by removing the sanitized branch name suffix from the channel if the branch is `v1.4`
=> fix: Fixes charm publishing

.github/workflows/update-libs.yaml
`github.actor` variables currently points to a person who last modified the cron expression for the workflow. This makes the jobs for auto-approve and auto-merge very fragile. 
This PR removes the condition. CI will make sure no breaking changes are introduced.
=> chore: Approves the PR and enables auto-merge of libs regardless of the actor

.github/workflows/publish-rock.yaml, .github/workflows/scan-rock.yaml
The versions of skopeo from universe and snap store are too old to work with recentl docker revisions. The rockcraft team noticed this and now bundle a version of skopeo that will work with newer docker engines
=> fix: update workflow to use rockcraft.skopeo

.github/workflows/update-libs.yaml
- Adds `automerge` label to PRs updating libs
- Adds condition to auto approve and auto merge steps. Now they'll run only if a PR has been created
=> chore: Adds automerge label to PRs updating libs

.github/workflows/integration-test.yaml
The new minor version (should definitely have been a major version) of upload-artifact came with a breaking change where it does not include hidden files by default. This caused our publishing CI to fail.
- https://github.com/actions/upload-artifact/releases/tag/v4.4.0
=> chore: Include hidden files in upload artifacts.

.github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml, .github/workflows/lint-report.yaml, .github/workflows/static-analysis.yaml, .github/workflows/unit-test.yaml
Adds support for `uv` and move to concierge to setup the integration testing environment.
The move to concierge enables us to install `tox` with `uv` support cleanly. It also enables running the same locally for testing.
This will work for all projects, even if they are not yet migrated to `uv`. Once this is merged, tag `v2.0.0` will be created to enable including these changes in sdcore projects.
=> chore: Add support for uv and move to concierge

.github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
We decided to use Juju 3.5 in SD-Core 1.5 channel. The reason why this PR updates the Juju version in CI workflows.
=> chore: update Juju version to 3.5 in the workflows

.github/workflows/build.yaml, .github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
Updates the workflows to use the latest stable releases of dependencies or LTS releases. Specifically:
- MicroK8s 1.31-strict (latest stable release)
- LXD 5.21 (latest LTS release)
Once merged, this will be tagged `v2.1.0`.
=> chore: Update workflows to latest stable releases or LTS releases

.github/workflows/integration-test-machine.yaml, .github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
Removes `concierge` and add back `actions-operator` to stabilize CI.
Tested [here](https://github.com/canonical/sdcore-amf-k8s-operator/pull/464)
=> chore: Rollback concierge to stabilize CI

.github/workflows/build.yaml
Adds possibility of passing arbitrary branch to the build workflow
This feature is needed to run scheduled CI against the release branches.
=> feat: Adds possibility of passing arbitrary branch to the build workflow

.github/workflows/scan-rock.yaml
SEC0026 - SSDLC - Vulnerability Response requires to report the list of Known Exploited Vulnerabilities catalog (KEV) as a part of image scan process. The scan-rock workflow already reports the CVEs.  However, it was not reporting KEVs. 
Within this PR, KEVs are detected and reported in the Github Security tab. Besides,
CVEs and KEVs are uploaded as artifacts.
The PR: https://github.com/canonical/sdcore-amf-rock/pull/50#pullrequestreview-2722043096 tests the scan-rock workflow in sdcore-amf-rock repository.
=> chore: report KEVs after scanning images

.github/workflows/scan-rock.yaml
This PR enhances the `compare found CVEs with KEVs` step in scan-rock workflow.
Here are the improvements:
1. It does not show any CVE or KEV details while logging.
2. It does not upload sarif files as artifacts. Otherwise, people can download those files and read them.
3. If any KEV does not match with CVE, uploading KEV sarif file to GH security tab is skipped.
4. The script stops immediately on errors.
5. It catches pipeline (concatenated commands) related errors.
6. Log the errors before terminating the script.
7. If a command fails `set -e` triggers the ERR signal and `trap` catches the errors. 
Then, `trap` calls the `error_exit` function that logs the errors. The script terminates after logging.
https://github.com/canonical/sdcore-amf-rock/pull/50 tests the latest version of the …
=> chore: do not show CVE, KEV details while logging

.github/workflows/integration-test.yaml
This PR fixes an issue for which Juju is not able to bootstrap `k8s` cloud due to missing `~/.kube/config` file.
=> fix: save K8s config allowing Juju to read it

renovate.json5
When running locally a simulation of renovate on any repo, I get the following output:
```
$ RENOVATE_CONFIG_FILE=.github/renovate.json5 npx renovate --token="${GITHUB_TOKEN}" --schedule="after 1am and before 3am every monday" --require-config="ignored" --dry-run="full" canonical/sdcore-amf-k8s-operator
...
WARN: Invalid schedule: Failed to parse "after 1am and before 2am every monday" (repository=canonical/sdcore-amf-k8s-operator, branch=renovate/github-actions)
INFO: DRY-RUN: Would commit files to branch renovate/github-actions (repository=canonical/sdcore-amf-k8s-operator, branch=renovate/github-actions)
WARN: Invalid schedule: Failed to parse "after 1am and before 2am every monday" (repository=canonical/sdcore-amf-k8s-operator, branch=renovate/major-python-dependencies)
INFO: DRY-RUN: …
```
=> fix: use valid Renovate schedule

.github/workflows/integration-test-with-multus.yaml, .github/workflows/integration-test.yaml
This PR adds `jhack` to the integration tests to allow testing the HA scenario and aligns Canonical K8s version to the one used by E2E tests.
=> feat: add Jhack to integration tests and bump K8s version
