canonical/sdcore-github-workflows

.github/workflows/publish-lib.yaml
CODEOWNERS

- Adds workflow for publishing libs
- Adds CODEOWNERS

Adding publish-lib workflow

---

.github/workflows/check-libraries.yaml

Adds a workflow file for the check-libraries action.

Adds check libraries workflow

---

.github/workflows/check-libraries.yaml

Fixes a minor indentation issue in the check libraries workflow file.

Fixes a minor identation issue

---

.github/workflows/build-rock.yaml
.github/workflows/publish-rock.yaml
.github/workflows/scan-rock.yaml

Adds common workflow files of the SDCORE ROCKs to manage them centrally.

Adds workflow files for SDCORE ROCKs

---

.github/workflows/integration-test.yaml

Adds the option to enable metallb microk8s addon in integration tests

[Feat] Adds option to enable metallb microk8s addon in integration tests

---

.github/workflows/build-rock.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/integration-test-with-multus.yaml
.github/workflows/integration-test.yaml
.github/workflows/lint-report.yaml
.github/workflows/promote.yaml
.github/workflows/publish-charm.yaml
.github/workflows/publish-lib.yaml
.github/workflows/publish-rock.yaml
.github/workflows/scan-rock.yaml
.github/workflows/static-analysis.yaml
.github/workflows/unit-test.yaml

- Enables `metallb` in `integration-test-with-multus` workflow.
- Replaces hash for the `checkout` action with simple `v4`

Adding metallb

---

.github/workflows/publish-charm.yaml
.github/workflows/publish-lib.yaml
.github/workflows/publish-rock.yaml

Adds step archiving Charmcraft logs in case publishing fails.

Archive charmcraft logs if publishing fails

---

.github/workflows/promote.yaml
.github/workflows/publish-charm.yaml

Changes the track where the charms are published from latest to 1.3 by default

feat: TELCO-948 Use variable for the track for charms

---

.github/workflows/integration-test-machine.yaml

Add workflow for integration tests with machine charms which will be used by the UPF machine charm.

feat: Add workflow for integration tests with machine charms

---

.github/workflows/terraform.yaml

Adding workflow for Terraform module checks.

feat: Adding workflow for Terraform module checks

---

.github/workflows/build-rock.yaml
.github/workflows/check-libraries.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/integration-test-machine.yaml
.github/workflows/integration-test-with-multus.yaml
.github/workflows/integration-test.yaml
.github/workflows/issues.yaml
.github/workflows/lint-report.yaml
.github/workflows/promote.yaml
.github/workflows/publish-charm.yaml
.github/workflows/publish-lib.yaml
.github/workflows/publish-rock.yaml
.github/workflows/scan-rock.yaml
.github/workflows/static-analysis.yaml
.github/workflows/terraform.yaml
.github/workflows/unit-test.yaml
LICENSE

- Refactoring the steps of workflow file for Terraform checks.
- Adding LICENSE file
-  Adding license headers for the workflow files

chore: Rename the Terraform workflow file steps

---

.github/workflows/dependabot_pr.yaml

Add common workflow for auto-merging dependabot prs

chore: add workflow for auto-merging dependabot prs

---

.github/workflows/lint-pr.yaml

chore: add pr title validation

---

.github/workflows/promote.yaml

Allows promotion from `beta` to `stable`

chore: Allow promotion from beta to stable

---

.github/workflows/update-libs.yaml

chore: Adding update-libs workflow

---

.github/workflows/update-libs.yaml

Enabling auto merge and auto approve for libs updates

chore: Enabling auto merge and auto approve for libs updates

---

.github/workflows/publish-charm.yaml

Changes double quotes to single quotes to make GH happy (double quotes produce syntax error)

fix: Changes double quotes to single quotes to make GH happy

---

.github/workflows/update-libs.yaml

Adds `v1.4` label to auto-libs PRs

chore: Adds v1.4 label to auto-libs PRs

---

.github/workflows/integration-test-machine.yaml
.github/workflows/integration-test-with-multus.yaml

PR #75 added inclusion of hidden files when running integration tests. Here we add this same parameter for running integration tests with multus and with the machine charm.

chore: add include hidden files (pt.2)

---

.github/workflows/integration-test-with-multus.yaml

Enables missing Microk8s addons

fix: Enables missing Microk8s addons

---

.github/workflows/integration-test-machine.yaml
.github/workflows/integration-test-with-multus.yaml
.github/workflows/integration-test.yaml

Bump juju to the latest stable release: 3.6/stable.

chore: bump juju to 3.6/stable

---

.github/workflows/build-rock.yaml
.github/workflows/scan-rock.yaml

Adds support for building and scanning rocks using a custom branch

feat: Adds support for building and scanning rocks using a custom branch
